package baml_go

// ToolchainVersion is the canonical BAML toolchain whose generated bytecode
// this module accepts. BridgeRuntimeVersion preserves Go's published v prefix.
const BridgeRuntimeName = "github.com/boundaryml/baml-go"
const ToolchainVersion = "0.17.1-nightly.20260824.b"
const BridgeRuntimeVersion = "v0.17.1-nightly.20260824.b"
const DefaultRuntimeVersion = ToolchainVersion

func requiredRuntimeVersion() string {
	return ToolchainVersion
}

func GetToolchainVersion() string     { return ToolchainVersion }
func GetBridgeRuntimeVersion() string { return BridgeRuntimeVersion }
